services:
  data-processing-service:
    build:
      context: ./DataProcessingService
      dockerfile: Dockerfile
    container_name: data-processing-service
    expose:
      - 5075
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5075

  data-processing-spa:
    build:
      context: ./data-processing-spa
      dockerfile: Dockerfile
    container_name: data-processing-spa
    volumes:
      - frontend-build:/app/dist
    command: ["sh", "-c", "npm install && npm run build -- --configuration=production"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - frontend-build:/frontend-full:ro
    depends_on:
      - data-processing-service
      - data-processing-spa

volumes:
  frontend-build: